- hosts: prod
  become: true
  tasks:
      - name: Installing prod dependencies
        apt:
            name:
                - python3
                - python3-pip
                - docker.io
            state: present
